// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQIEcMmsxlu51qkXlYiMD4KuaLt_M3MPo',
    appId: '1:671136010570:android:c1aec90e7dc3a12e7eb1b3',
    messagingSenderId: '671136010570',
    projectId: 'esco-vip-chauffeur',
    storageBucket: 'esco-vip-chauffeur.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQIEcMmsxlu51qkXlYiMD4KuaLt_M3MPo',
    appId: '1:671136010570:ios:8b709930ded151687eb1b3',
    messagingSenderId: '671136010570',
    projectId: 'esco-vip-chauffeur',
    storageBucket: 'esco-vip-chauffeur.firebasestorage.app',
    iosBundleId: 'com.vipchauffeur.chauffeur',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQIEcMmsxlu51qkXlYiMD4KuaLt_M3MPo',
    appId: '1:671136010570:web:631e1bcaf4335e627eb1b3',
    messagingSenderId: '671136010570',
    projectId: 'esco-vip-chauffeur',
    storageBucket: 'esco-vip-chauffeur.firebasestorage.app',
    authDomain: 'esco-vip-chauffeur.firebaseapp.com',
  );
}
